MODEL:
  TYPE: 'RetinaNet'
  CONV_BODY: 'ResNet50_FPN'
  NUM_CLASSES: 20
RETINANET:
  RETINANET_ON: True
  LOSS_ALPHA: 0.25
  LOSS_GAMMA: 2.0
  NUM_CONVS: 4
  ASPECT_RATIOS: (0.5, 1, 2.0)
  ANCHOR_SCALE: 4
  SCALE_RATIOS: (1.0, 1.2599210498948732, 1.5874010519681994)
  PRIOR_PROB: 0.01
SOLVER:
  BASE_LR: 0.001
  OPTIMIZER: 'sgd'
  MOMENTUM: 0.9
  MAX_ITER: 300
  WEIGHT_DECAY: 0.0001
TRAIN:
  WEIGHTS: 'init.pth'
  DATASETS: ('VOC2012','train.txt')
  DATASETS_DIR: '/home/changq/Projects/VOCdevkit/'
  SAVE_CHECKPOINTS_EPOCHS: 10
  MAX_EPOCHS: 30
  BATCH_SIZE: 8
  SCALES: (600,600)
  AUTO_RESUME: True
  RESUME_FILE: 'ckpt_20.pth'
TEST:
  WEIGHTS: 'resume.pth'
  DATASETS: ('VOC2012','test.txt')
  DATASETS_DIR: '/home/changq/Projects/VOCdevkit_test/'
  SCALES: (600,600)
  OUTPUT_DIR: './result/'

